### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by KaChunWuGary** [KaChunWuGary/prework-study-guide#1]
#HTML

## User Story
As a bootcamp student
I want the prework notes to be structured on a webpage so that I can easily find and 
read information

## Acceptance Criteria 
GIVEN a Prework Study Guide website
WHEN I visit the website in my browser
THEN I see four boxes titled HTML, CSS, GIT, and JavaScript with associated notes listed

**Comment by theayazsoomro** [comment]
- This is a basic HTML structure with minimal styling.

`<!DOCTYPE html>
 <html lang="en">
 <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prework Study Guide</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }

       header {
            background-color: #333;
            color: #fff;
            padding: 1rem;
            text-align: center;
        }

        main {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        section {
            margin-bottom: 20px;
        }

        h2 {
            color: #333;
        }

        ul {
            list-style-type: none;
            padding: 0;
        }

        li {
            margin-bottom: 10px;
        }
    </style>
</head>
<body>

    <header>
        <h1>Prework Study Guide</h1>
    </header>

    <main>
        <section>
            <h2>HTML</h2>
            <ul>
                <li>HTML Basics</li>
                <li>HTML Elements and Tags</li>
                <li>HTML Forms</li>
                
            </ul>
        </section>

        <section>
            <h2>CSS</h2>
            <ul>
                <li>CSS Selectors</li>
                <li>Box Model</li>
                <li>CSS Flexbox and Grid</li>
                
            </ul>
        </section>

        <section>
            <h2>GIT</h2>
            <ul>
                <li>GIT Basics</li>
                <li>Version Control</li>
                <li>Branching and Merging</li>
                
            </ul>
        </section>

        <section>
            <h2>JavaScript</h2>
            <ul>
                <li>JavaScript Variables and Data Types</li>
                <li>Functions and Control Flow</li>
                <li>DOM Manipulation</li>
                
            </ul>
        </section>
    </main>

</body>
</html>`
